export enum MemberActions {
    SET_MEMBERS,
    SET_MEMBER,
    DELETE_MEMBER ,
    DELETE_MEMBER_FAILED,
    MEMBERS_EMPTY ,
    MEMBER_DELETED ,
    FETCH_MEMBERS_START ,
    FETCH_MEMBERS_FAILED ,
    FETCH_MEMBERS_FINISHED,
    ADD_MEMBER,
    ADD_MEMBER_SUCCESS,
    ADD_MEMBER_FAILED,
  
}


export enum ProjectActions {
    SET_PROJECTS = 'SET_PROJECTS',
    FETCH_PROJECTS_FAILED = 'FETCH_PROJECTS_FAILED',
    FETCH_PROJECTS_FINISHED = 'FETCH_PROJECTS_FINISHED',
    FETCH_PROJECTS_START = 'FETCH_PROJECTS_START',
    ADD_PROJECT = 'ADD_PROJECT',
    ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS',
    ADD_PROJECT_FAILED = 'ADD_PROJECT_FAILED',
    SET_PROJECT = 'SET_PROJECT',
    DELETE_PROJECT = 'DELETE_PROJECT',
    DELETE_PROJECT_FAILED = 'DELETE_PROJECT_FAILED',
    PROJECTS_EMPTY = 'PROJECTS_EMPTY',
    PROJECT_DELETED = 'PROJECT_DELETED',
  
}



